steps:
  - name: maven:3.9.6-eclipse-temurin-17-alpine
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/search-service:v1", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/search-service:v1']
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
    - run
    - --filename=./manifest/
    - --image=us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/search-service:v1
    - --location=us-central1
    - --cluster=amcart-cluster
images:
- 'us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/search-service:v1'
options:
  logging: CLOUD_LOGGING_ONLY