
kind: Service
apiVersion: v1
metadata:
  name: searchservice
spec:
  type: LoadBalancer
  selector:
    app: search-service
  ports:
    - port: 8081
      targetPort: 8081

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
data:
  elastic_search_host: 'elasticsearch'
  elastic_search_port: '9200'
  elastic_search_scheme: 'http'
  elastic_search_username: 'elastic'

---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
data:
  elastic_search_password: YWRtaW5AMTIz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image:  us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/search-service:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: search-config
            - secretRef:
                name: search-secret
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"  # Request 64 MiB of memory
              cpu: "250m"      # Request 250 milliCPU (0.25 CPU core)
            limits:
              memory: "1Gi"  # Limit memory usage to 128 MiB
              cpu: "500m"